spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /account

tomcat:
  ajp:
    port: 8002
    remoteauthentication: false
    enabled: true

SKM:
  Url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/{appkey}/secrets/{keyid}